force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Altura__c.field-meta.xml
<CustomField>
    <fullName>Altura__c</fullName>
    <label>Altura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Foto_URL__c.field-meta.xml
<CustomField>
    <fullName>Foto_URL__c</fullName>
    <label>Foto URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Geracao__c.field-meta.xml
<CustomField>
    <fullName>Geracao__c</fullName>
    <label>Geração</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PokmenonBatchTest.cls
@isTest
public with sharing class PokmenonBatchTest {
  @isTest
    static void testPokemonbatch() 
    {
        PokemonBatchMock mock = new PokemonBatchMock();
        PopulatePokemonBatch batch = new PopulatePokemonBatch();
        Test.setMock(HttpCalloutMock.class, mock);
        List<String> testData = new List<String>{
        'bulbasaur',
        'ivysaur',
        'venusaur',
        'charmander',
        'charmeleon',
        'charizard',
        'squirtle',
        'wartortle',
        'blastoise',
        'caterpie'
        };

        Test.startTest();
        Iterable<String> scope = batch.start(null);
        batch.execute(null, testData);
        Test.stopTest();
        List<Pokemon__c> pokemonList = [
        SELECT Name, Peso__c, Altura__c, Tipo__c, Geracao__c, Foto_URL__c
        FROM Pokemon__c];
        System.assertEquals(10, pokemonList.size());
    }
}