force-app/main/default/objects/Pokemon__c/Pokemon__c.object-meta.xml
<CustomObject>
    <label>Pokemon</label>
    <nameField>
        <label>Pokemon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pokemons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pokemon__c/fields/Altura__c.field-meta.xml
<CustomField>
    <fullName>Altura__c</fullName>
    <label>Altura</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Foto_URL__c.field-meta.xml
<CustomField>
    <fullName>Foto_URL__c</fullName>
    <label>Foto URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Geracao__c.field-meta.xml
<CustomField>
    <fullName>Geracao__c</fullName>
    <label>Geração</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Peso__c.field-meta.xml
<CustomField>
    <fullName>Peso__c</fullName>
    <label>Peso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/PokeIndex__c.field-meta.xml
<CustomField>
    <fullName>PokeIndex__c</fullName>
    <label>PokeIndex</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pokemon__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Fighting</fullName>
            </value>
            <value>
                <fullName>Flying</fullName>
            </value>
            <value>
                <fullName>Poison</fullName>
            </value>
            <value>
                <fullName>Ground</fullName>
            </value>
            <value>
                <fullName>Rock</fullName>
            </value>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Ghost</fullName>
            </value>
            <value>
                <fullName>Steel</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Water</fullName>
            </value>
            <value>
                <fullName>Grass</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Psychic</fullName>
            </value>
            <value>
                <fullName>Ice</fullName>
            </value>
            <value>
                <fullName>Dragon</fullName>
            </value>
            <value>
                <fullName>Dark</fullName>
            </value>
            <value>
                <fullName>Fairy</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PopulatePokemonBatch.cls
public class PopulatePokemonBatch implements Database.Batchable<String>, Database.AllowsCallouts {
  public Iterable<String> start(Database.BatchableContext bc) {
    List<String> pokeList = new List<String>();
    //Make API call
    Http http = new Http();
    HttpRequest request = new HttpRequest();
    request.setEndpoint('https://pokeapi.co/api/v2/pokemon?limit=905');
    request.setMethod('GET');
    HttpResponse response = http.send(request);
    // Check if Connection was successful
    if (response.getStatusCode() == 200) {
      //deserialize response
      Map<String, Object> responseData = (Map<String, Object>) JSON.deserializeUntyped(
        response.getBody()
      );
      List<Object> results = (List<Object>) responseData.get('results');
      //get url of pokemon's endpoints
      for (Object result : results) {
        Map<String, Object> pokemonData = (Map<String, Object>) result;
        String pokeName = (String) pokemonData.get('name');
        pokeList.add(pokeName);
      }
    }
    return pokeList;
  }

  public void execute(Database.BatchableContext bc, List<String> scope) {
    try {
      List<Pokemon__c> pokemonList = new List<Pokemon__c>();
      for (String record : scope) {
        String pokeName = record;
        HttpRequest detailsRequest = new HttpRequest();
        detailsRequest.setEndpoint(
          'https://pokeapi.co/api/v2/pokemon/' + pokeName
        );
        detailsRequest.setMethod('GET');
        HttpResponse detailsResponse = new Http().send(detailsRequest);
        // Check if Connection to the new endpoint was successful
        if (detailsResponse.getStatusCode() == 200) {
          //deserialize response
          Map<String, Object> detailData = (Map<String, Object>) JSON.deserializeUntyped(
            detailsResponse.getBody()
          );
          // get fields from detail data
          //***** get the id
          Integer id = (Integer) detailData.get('id');
          //***** Check if the id is greater than the number of pokemons we want to get
          //***** we only want the pokemons until the 8th generation

          //***** get and convert height and weight to the correct units
          Double height = (Double) detailData.get('height') / 10;
          Double weight = (Double) detailData.get('weight') / 10;
          //***** get the name
          // String name = (String) detailData.get('name');
          //***** get and handle multiple types
          List<Object> types = (List<Object>) detailData.get('types');
          List<String> typeList = new List<String>();
          for (Object type : types) {
            Map<String, Object> typeData = (Map<String, Object>) type;
            Map<String, Object> typeName = (Map<String, Object>) typeData.get(
              'type'
            );
            String nameType = (String) typeName.get('name');
            typeList.add(nameType);
          }
          //***** get species url to adquire the generation
          Map<String, Object> species = (Map<String, Object>) detailData.get(
            'species'
          );
          String speciesUrl = (String) species.get('url');
          // make a call to the species endpoint
          HttpRequest speciesRequest = new HttpRequest();
          speciesRequest.setEndpoint(speciesUrl);
          speciesRequest.setMethod('GET');
          HttpResponse speciesResponse = new Http().send(speciesRequest);
          // Check if Connection to the new endpoint was successful
          if (speciesResponse.getStatusCode() == 200) {
            //deserialize response
            Map<String, Object> speciesDetails = (Map<String, Object>) JSON.deserializeUntyped(
              speciesResponse.getBody()
            );
            //***** get the generation url and extract the the generation number from the end
            Map<String, Object> generationDetails = (Map<String, Object>) speciesDetails.get(
              'generation'
            );
            String generationUrl = (String) generationDetails.get('url');
            String generation = generationUrl.substring(
              generationUrl.length() - 2,
              generationUrl.length() - 1
            );
            //***** get the sprites
            Map<String, Object> sprites = (Map<String, Object>) detailData.get(
              'sprites'
            );
            String spriteUrl = (String) sprites.get('front_default');
            //***** create a new pokemon object and insert the data extrated fom the API
            Pokemon__c pokemon = new Pokemon__c(
              Name = pokeName.capitalize(),
              PokeIndex__c = id,
              Peso__c = String.valueOf(weight + ' kg'),
              Altura__c = String.valueOf(height + ' mts'),
              Tipo__c = String.join(typeList, ';'),
              Geracao__c = Integer.valueOf(generation),
              Foto_URL__c = spriteUrl
            );
            pokemonList.add(pokemon);
          }
        }
      }
      if (!pokemonList.isEmpty()) {
        insert pokemonList;
      }
    } catch (Exception e) {
      System.debug('Error: ' + e.getMessage());
    }
  }

  public void finish(Database.BatchableContext bc) {
    system.debug('batch finished');
  }
}